# Generated by Django 5.0.7 on 2024-07-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
