# Generated by Django 5.0.7 on 2024-07-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0005_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='protector_comment',
            field=models.TextField(blank=True),
        ),
    ]
