# Generated by Django 5.0.7 on 2024-07-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_request_pending',
            field=models.BooleanField(default=False),
        ),
    ]
