# Generated by Django 5.0.7 on 2024-07-20 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_is_request_pending'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_request_pending',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_protector_requests',
            field=models.ManyToManyField(blank=True, related_name='pending_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
