# Generated by Django 5.0.7 on 2024-07-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_is_request_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='protectors',
            field=models.ManyToManyField(blank=True, related_name='protected_seniors', to='accounts.userprofile'),
        ),
    ]
