# Generated by Django 5.0.7 on 2024-07-21 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_protectors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='protectors',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='senior_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protector_userprofiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
