# Generated by Django 5.0.7 on 2024-07-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_userprofile_protectors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='relationship',
            field=models.CharField(blank=True, choices=[('자녀', '자녀'), ('친구', '친구'), ('배우자', '배우자'), ('간병인', '간병인'), ('기타', '기타')], max_length=10, null=True),
        ),
    ]
