# Generated by Django 5.0.7 on 2024-07-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_emotion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emotion',
        ),
    ]
