# Generated by Django 5.0.7 on 2024-07-27 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_userprofile_pending_protector_requests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pending_protector_requests',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='senior_user',
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('자녀', '자녀'), ('친구', '친구'), ('배우자', '배우자'), ('간병인', '간병인'), ('기타', '기타')], max_length=10)),
                ('pending', models.BooleanField(default=True)),
                ('protector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senior_relationships', to='accounts.userprofile')),
                ('senior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protector_relationships', to='accounts.userprofile')),
            ],
        ),
    ]
